# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mneris/Development/game-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mneris/Development/game-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mneris/Development/game-engine/CMakeFiles /Users/mneris/Development/game-engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mneris/Development/game-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lua-tutorial

# Build rule for target.
lua-tutorial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua-tutorial
.PHONY : lua-tutorial

# fast build rule for target.
lua-tutorial/fast:
	$(MAKE) -f CMakeFiles/lua-tutorial.dir/build.make CMakeFiles/lua-tutorial.dir/build
.PHONY : lua-tutorial/fast

#=============================================================================
# Target rules for targets named ray_trace_dod

# Build rule for target.
ray_trace_dod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ray_trace_dod
.PHONY : ray_trace_dod

# fast build rule for target.
ray_trace_dod/fast:
	$(MAKE) -f CMakeFiles/ray_trace_dod.dir/build.make CMakeFiles/ray_trace_dod.dir/build
.PHONY : ray_trace_dod/fast

#=============================================================================
# Target rules for targets named ray_trace_oop

# Build rule for target.
ray_trace_oop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ray_trace_oop
.PHONY : ray_trace_oop

# fast build rule for target.
ray_trace_oop/fast:
	$(MAKE) -f CMakeFiles/ray_trace_oop.dir/build.make CMakeFiles/ray_trace_oop.dir/build
.PHONY : ray_trace_oop/fast

#=============================================================================
# Target rules for targets named swap_chain_test

# Build rule for target.
swap_chain_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swap_chain_test
.PHONY : swap_chain_test

# fast build rule for target.
swap_chain_test/fast:
	$(MAKE) -f CMakeFiles/swap_chain_test.dir/build.make CMakeFiles/swap_chain_test.dir/build
.PHONY : swap_chain_test/fast

#=============================================================================
# Target rules for targets named tinyxml_static

# Build rule for target.
tinyxml_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml_static
.PHONY : tinyxml_static

# fast build rule for target.
tinyxml_static/fast:
	$(MAKE) -f tinyxml/CMakeFiles/tinyxml_static.dir/build.make tinyxml/CMakeFiles/tinyxml_static.dir/build
.PHONY : tinyxml_static/fast

#=============================================================================
# Target rules for targets named collada-compiler

# Build rule for target.
collada-compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collada-compiler
.PHONY : collada-compiler

# fast build rule for target.
collada-compiler/fast:
	$(MAKE) -f collada/CMakeFiles/collada-compiler.dir/build.make collada/CMakeFiles/collada-compiler.dir/build
.PHONY : collada-compiler/fast

#=============================================================================
# Target rules for targets named collada_static

# Build rule for target.
collada_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collada_static
.PHONY : collada_static

# fast build rule for target.
collada_static/fast:
	$(MAKE) -f collada/CMakeFiles/collada_static.dir/build.make collada/CMakeFiles/collada_static.dir/build
.PHONY : collada_static/fast

#=============================================================================
# Target rules for targets named lua_static

# Build rule for target.
lua_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua_static
.PHONY : lua_static

# fast build rule for target.
lua_static/fast:
	$(MAKE) -f lua/CMakeFiles/lua_static.dir/build.make lua/CMakeFiles/lua_static.dir/build
.PHONY : lua_static/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named engine_static

# Build rule for target.
engine_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_static
.PHONY : engine_static

# fast build rule for target.
engine_static/fast:
	$(MAKE) -f engine/CMakeFiles/engine_static.dir/build.make engine/CMakeFiles/engine_static.dir/build
.PHONY : engine_static/fast

#=============================================================================
# Target rules for targets named json_static

# Build rule for target.
json_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_static
.PHONY : json_static

# fast build rule for target.
json_static/fast:
	$(MAKE) -f engine/CMakeFiles/json_static.dir/build.make engine/CMakeFiles/json_static.dir/build
.PHONY : json_static/fast

#=============================================================================
# Target rules for targets named protocol_static

# Build rule for target.
protocol_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protocol_static
.PHONY : protocol_static

# fast build rule for target.
protocol_static/fast:
	$(MAKE) -f engine/CMakeFiles/protocol_static.dir/build.make engine/CMakeFiles/protocol_static.dir/build
.PHONY : protocol_static/fast

#=============================================================================
# Target rules for targets named socket_static

# Build rule for target.
socket_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_static
.PHONY : socket_static

# fast build rule for target.
socket_static/fast:
	$(MAKE) -f engine/CMakeFiles/socket_static.dir/build.make engine/CMakeFiles/socket_static.dir/build
.PHONY : socket_static/fast

#=============================================================================
# Target rules for targets named stream_static

# Build rule for target.
stream_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_static
.PHONY : stream_static

# fast build rule for target.
stream_static/fast:
	$(MAKE) -f engine/CMakeFiles/stream_static.dir/build.make engine/CMakeFiles/stream_static.dir/build
.PHONY : stream_static/fast

#=============================================================================
# Target rules for targets named swap_chain_static

# Build rule for target.
swap_chain_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swap_chain_static
.PHONY : swap_chain_static

# fast build rule for target.
swap_chain_static/fast:
	$(MAKE) -f engine/CMakeFiles/swap_chain_static.dir/build.make engine/CMakeFiles/swap_chain_static.dir/build
.PHONY : swap_chain_static/fast

ray_trace_dod.o: ray_trace_dod.cpp.o
.PHONY : ray_trace_dod.o

# target to build an object file
ray_trace_dod.cpp.o:
	$(MAKE) -f CMakeFiles/ray_trace_dod.dir/build.make CMakeFiles/ray_trace_dod.dir/ray_trace_dod.cpp.o
.PHONY : ray_trace_dod.cpp.o

ray_trace_dod.i: ray_trace_dod.cpp.i
.PHONY : ray_trace_dod.i

# target to preprocess a source file
ray_trace_dod.cpp.i:
	$(MAKE) -f CMakeFiles/ray_trace_dod.dir/build.make CMakeFiles/ray_trace_dod.dir/ray_trace_dod.cpp.i
.PHONY : ray_trace_dod.cpp.i

ray_trace_dod.s: ray_trace_dod.cpp.s
.PHONY : ray_trace_dod.s

# target to generate assembly for a file
ray_trace_dod.cpp.s:
	$(MAKE) -f CMakeFiles/ray_trace_dod.dir/build.make CMakeFiles/ray_trace_dod.dir/ray_trace_dod.cpp.s
.PHONY : ray_trace_dod.cpp.s

ray_trace_oop.o: ray_trace_oop.cpp.o
.PHONY : ray_trace_oop.o

# target to build an object file
ray_trace_oop.cpp.o:
	$(MAKE) -f CMakeFiles/ray_trace_oop.dir/build.make CMakeFiles/ray_trace_oop.dir/ray_trace_oop.cpp.o
.PHONY : ray_trace_oop.cpp.o

ray_trace_oop.i: ray_trace_oop.cpp.i
.PHONY : ray_trace_oop.i

# target to preprocess a source file
ray_trace_oop.cpp.i:
	$(MAKE) -f CMakeFiles/ray_trace_oop.dir/build.make CMakeFiles/ray_trace_oop.dir/ray_trace_oop.cpp.i
.PHONY : ray_trace_oop.cpp.i

ray_trace_oop.s: ray_trace_oop.cpp.s
.PHONY : ray_trace_oop.s

# target to generate assembly for a file
ray_trace_oop.cpp.s:
	$(MAKE) -f CMakeFiles/ray_trace_oop.dir/build.make CMakeFiles/ray_trace_oop.dir/ray_trace_oop.cpp.s
.PHONY : ray_trace_oop.cpp.s

swap_chain_test.o: swap_chain_test.cpp.o
.PHONY : swap_chain_test.o

# target to build an object file
swap_chain_test.cpp.o:
	$(MAKE) -f CMakeFiles/swap_chain_test.dir/build.make CMakeFiles/swap_chain_test.dir/swap_chain_test.cpp.o
.PHONY : swap_chain_test.cpp.o

swap_chain_test.i: swap_chain_test.cpp.i
.PHONY : swap_chain_test.i

# target to preprocess a source file
swap_chain_test.cpp.i:
	$(MAKE) -f CMakeFiles/swap_chain_test.dir/build.make CMakeFiles/swap_chain_test.dir/swap_chain_test.cpp.i
.PHONY : swap_chain_test.cpp.i

swap_chain_test.s: swap_chain_test.cpp.s
.PHONY : swap_chain_test.s

# target to generate assembly for a file
swap_chain_test.cpp.s:
	$(MAKE) -f CMakeFiles/swap_chain_test.dir/build.make CMakeFiles/swap_chain_test.dir/swap_chain_test.cpp.s
.PHONY : swap_chain_test.cpp.s

tutorial.o: tutorial.cpp.o
.PHONY : tutorial.o

# target to build an object file
tutorial.cpp.o:
	$(MAKE) -f CMakeFiles/lua-tutorial.dir/build.make CMakeFiles/lua-tutorial.dir/tutorial.cpp.o
.PHONY : tutorial.cpp.o

tutorial.i: tutorial.cpp.i
.PHONY : tutorial.i

# target to preprocess a source file
tutorial.cpp.i:
	$(MAKE) -f CMakeFiles/lua-tutorial.dir/build.make CMakeFiles/lua-tutorial.dir/tutorial.cpp.i
.PHONY : tutorial.cpp.i

tutorial.s: tutorial.cpp.s
.PHONY : tutorial.s

# target to generate assembly for a file
tutorial.cpp.s:
	$(MAKE) -f CMakeFiles/lua-tutorial.dir/build.make CMakeFiles/lua-tutorial.dir/tutorial.cpp.s
.PHONY : tutorial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lua-tutorial"
	@echo "... ray_trace_dod"
	@echo "... ray_trace_oop"
	@echo "... rebuild_cache"
	@echo "... swap_chain_test"
	@echo "... tinyxml_static"
	@echo "... collada-compiler"
	@echo "... collada_static"
	@echo "... lua_static"
	@echo "... engine"
	@echo "... engine_static"
	@echo "... json_static"
	@echo "... protocol_static"
	@echo "... socket_static"
	@echo "... stream_static"
	@echo "... swap_chain_static"
	@echo "... ray_trace_dod.o"
	@echo "... ray_trace_dod.i"
	@echo "... ray_trace_dod.s"
	@echo "... ray_trace_oop.o"
	@echo "... ray_trace_oop.i"
	@echo "... ray_trace_oop.s"
	@echo "... swap_chain_test.o"
	@echo "... swap_chain_test.i"
	@echo "... swap_chain_test.s"
	@echo "... tutorial.o"
	@echo "... tutorial.i"
	@echo "... tutorial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

